step_up:
  name: Step Up
  description: Increase brightness by one step along the glo curve
  icon: mdi:brightness-5
  fields:
    area_id:
      name: Area
      description: The area(s) to control
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

step_down:
  name: Step Down
  description: Decrease brightness by one step along the glo curve
  icon: mdi:brightness-4
  fields:
    area_id:
      name: Area
      description: The area(s) to control
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

reset:
  name: Reset
  description: Turn on lights to glo of current time, enable HomeGlo
  icon: mdi:restore
  fields:
    area_id:
      name: Area
      description: The area(s) to reset
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

homeglo_on:
  name: HomeGlo On
  description: Turn on lights to last state and enable HomeGlo glo mode for an area
  icon: mdi:lightbulb-on
  fields:
    area_id:
      name: Area
      description: The area(s) to enable HomeGlo for
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

homeglo_off:
  name: HomeGlo Off
  description: Turn off lights and disable HomeGlo for an area
  icon: mdi:lightbulb-off
  fields:
    area_id:
      name: Area
      description: The area(s) to turn off and disable HomeGlo for
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

homeglo_deactivate:
  name: HomeGlo Deactivate
  description: Disable HomeGlo for an area (lights remain in current state)
  icon: mdi:lightbulb-off-outline
  fields:
    area_id:
      name: Area
      description: The area(s) to deactivate HomeGlo for (lights remain unchanged)
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true
