step_up:
  name: Step Up
  description: Increase brightness by one step along the adaptive lighting curve
  fields:
    area_id:
      name: Area
      description: The area(s) to control
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true

step_down:
  name: Step Down
  description: Decrease brightness by one step along the adaptive lighting curve
  fields:
    area_id:
      name: Area
      description: The area(s) to control
      required: true
      example: ["living_room", "kitchen"]
      selector:
        area:
          multiple: true
