# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: MagicLight
version: "2.0.5"
slug: magiclight
description: Connects to Home Assistant WebSocket API and listens for switch events
url: "https://github.com/tkthundr/magic-light"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
auth_api: true
homeassistant_api: true
ingress: true
ingress_port: 8099
ingress_entry: /
panel_icon: mdi:lightbulb
panel_title: Light Designer
panel_admin: false
options:
  color_mode: "xy"
  min_color_temp: 500
  max_color_temp: 6500
schema:
  color_mode: list(kelvin|rgb|xy)
  min_color_temp: "int(153,9000)"
  max_color_temp: "int(153,9000)"
