# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Intuitive Light
version: "2.5.1"
slug: intuitivelight
description: Connects to Home Assistant WebSocket API and listens for switch events
url: "https://github.com/intuitivelight/intuitivelight-ha"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
auth_api: true
homeassistant_api: true
ingress: true
ingress_port: 8099
ingress_entry: /
panel_icon: mdi:lightbulb
panel_title: Intuitive Light
panel_admin: false
options:
  color_mode: "kelvin"
  min_color_temp: 500
  max_color_temp: 6500
schema:
  color_mode: list(kelvin|rgb|xy)
  min_color_temp: "int(153,9000)"
  max_color_temp: "int(153,9000)"
