name: Build Add-on

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, aarch64, armv7]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Build Add-on for ${{ matrix.arch }}
      run: |
        cd addon
        docker run --rm --privileged \
          -v "$(pwd)":/data \
          -v /var/run/docker.sock:/var/run/docker.sock:ro \
          ghcr.io/home-assistant/amd64-builder \
          -t /data \
          --test \
          --${{ matrix.arch }} \
          -i homeglo-${{ matrix.arch }} \
          -d local
    
    - name: Verify build
      run: |
        docker images | grep homeglo || exit 0
        echo "Build completed successfully for ${{ matrix.arch }}"