# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HomeGlo
version: "1.0.1"
slug: homeglo
description: Connects to Home Assistant WebSocket API and listens for switch events
url: "https://github.com/homeglo/homeglo-ha"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  host: "homeassistant.local"
  port: 8123
  token: ""
  use_ssl: false
schema:
  host: "str"
  port: "int"
  token: "str"
  use_ssl: "bool"
panel_icon: mdi:lightbulb
