# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HomeGlo WebSocket Listener
version: "1.0.0"
slug: homeglo_websocket
description: Connects to Home Assistant WebSocket API and listens for events
url: "https://github.com/yourusername/homeglo"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  host: "localhost"
  port: 8123
  token: ""
  use_ssl: false
schema:
  host: "str"
  port: "int"
  token: "str"
  use_ssl: "bool"
image: "ghcr.io/yourusername/{arch}-addon-homeglo"
