# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: HomeGlo
version: "1.3.2"
slug: homeglo
description: Connects to Home Assistant WebSocket API and listens for switch events
url: "https://github.com/homeglo/homeglo-ha"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
auth_api: true
homeassistant_api: true
panel_icon: mdi:lightbulb
options:
  color_mode: "rgb"
  min_color_temp: 500
  max_color_temp: 6500
  sun_cct_gamma: 0.9
  sun_brightness_gamma: 0.5
schema:
  color_mode: list(kelvin|rgb|xy)
  min_color_temp: "int(153,9000)"
  max_color_temp: "int(153,9000)"
  sun_cct_gamma: "float(0.1,5.0)"
  sun_brightness_gamma: "float(0.1,5.0)"
