blueprint:
  name: HomeGlo Smart Switch Control
  description: >
    Control lights with HomeGlo adaptive lighting using ZHA switch events.
    Maps switch button presses to HomeGlo primitives.
    
    Button mappings:
    - ON button single press: Toggle lights and HomeGlo (smart toggle)
    - OFF button single press: Reset to current time and enable HomeGlo
    - UP button single press: Step up brightness along glo curve
    - DOWN button single press: Step down brightness along glo curve
  domain: automation
  input:
    switch_device:
      name: Switch Device(s)
      description: The switch device(s) to use for controlling lights
      selector:
        device:
          multiple: true
    target_areas:
      name: Target Areas
      description: The area(s) to control when buttons are pressed
      selector:
        area:
          multiple: true

mode: restart
max_exceeded: silent

trigger:
  # ON button single press from any switch
  - platform: event
    event_type: zha_event
    event_data:
      command: "on_press"
    id: on_press
  
  # OFF button single press from any switch
  - platform: event
    event_type: zha_event
    event_data:
      command: "off_press"
    id: off_press
  
  # UP button single press from any switch
  - platform: event
    event_type: zha_event
    event_data:
      command: "up_press"
    id: up_press
  
  # DOWN button single press from any switch
  - platform: event
    event_type: zha_event
    event_data:
      command: "down_press"
    id: down_press

variables:
  areas: !input target_areas
  switches: !input switch_device

action:
  # Only proceed if the event came from one of our configured switches
  - condition: template
    value_template: >
      {% set switch_list = switches if switches is list else [switches] %}
      {{ trigger.event.data.device_id in switch_list }}
  - choose:
      # ON button: Toggle HomeGlo
      - conditions:
          - condition: trigger
            id: on_press
        sequence:
          - service: homeglo.homeglo_toggle
            data:
              area_id: "{{ areas }}"
      
      # OFF button: Reset
      - conditions:
          - condition: trigger
            id: off_press
        sequence:
          - service: homeglo.reset
            data:
              area_id: "{{ areas }}"
      
      # UP button: Step up
      - conditions:
          - condition: trigger
            id: up_press
        sequence:
          - service: homeglo.step_up
            data:
              area_id: "{{ areas }}"
      
      # DOWN button: Step down
      - conditions:
          - condition: trigger
            id: down_press
        sequence:
          - service: homeglo.step_down
            data:
              area_id: "{{ areas }}"